### ISSUE TITLE
Scratch editor is adding arbitrary characters in blank fields.

### ISSUE THREAD

**Issue by 1lgatto** [dylanonelson/sn-scratch-editor#36] opened 2022-03-14 10:20 UTC
See this
https://github.com/standardnotes/mobile/issues/572

**Comment by dylanonelson** [comment] 2022-03-14 15:15
Hey, thanks for opening an issue. I thought I had fixed this on iOS. Will take a look as soon as I can. It should be a small fix.

**Comment by 1lgatto** [comment] 2022-03-14 15:23
Thanks for your response! 
Looking forward to hear from you.

**Comment by dylanonelson** [comment] 2022-03-16 05:18
I believe this is fixed by a change that I just pushed out. I am not sure how long it will take for the update to make its way to your device. I’m going to leave this issue open for a few days and make sure it doesn’t crop up for me again. It would be great if you could confirm the fix once you see it.

**Comment by 1lgatto** [comment] 2022-03-23 08:27
As by now the bug still persists.

**Comment by dylanonelson** [comment] 2022-03-24 02:57
I closed it because I can no longer reproduce it on any of my devices. It’s possible you still haven’t gotten the update. Unfortunately, Standard Notes makes it hard to see which version of the extension you are running. I will try pushing out a way to make checking a bit easier.

To confirm, this is still happening for you when you create new notes? The fix will not remove the mis-coded characters that are already in your notes, it only prevents them from being inserted in the future.

If you want, you can try re-installing the extension. The most effective way to do this is from the browser UI at app.standardnotes.com, because the app seems to do some aggressive caching of the extension code. Re-installing Scratch, however, will confuse Standard Notes and you may have to reset the editor for your notes that were previously using it.

**Comment by 1lgatto** [comment] 2022-05-18 16:20
Seems fixed.

**Closed** 2022-05-18 16:20 UTC

**Comment by 1lgatto** [comment] 2022-05-21 11:12
Starting with the recent version 3.20.0, the bug is back.
